### ISSUE TITLE
how to use leica camera in aosp

### ISSUE THREAD

**Issue by Liangzaigrape** [xiaomi-unicorn-development/device_xiaomi_miuicamera-unicorn#1]
Hello, I noticed that you made a zip mask module for Leica camera for Mayfly's AOSP. I want to use Leica camera on my device on AOSP. Can I unzip your zip and replace the corresponding apk and so
![Screenshot_20240701-012101_MT管理器](https://github.com/xiaomi-unicorn-development/device_xiaomi_miuicamera-unicorn/assets/90471811/6ac9e847-b291-43a7-bef6-f169ec8b0321)
 files in it to make Leica camera run on AOSP on my device?

**Comment by RITEFANG** [comment]
Hi, of course you can use this but it's signed with keys, please use the other version.
And it's created by Arian.

当然可以，这个是有自动构建机器签名的，可以用另一个版本。而且它是Arian做的不是我做的。

Minus
